#!/bin/sh

FPDLURL="https://fpdownload.macromedia.com/pub/labs/flashruntimes/flashplayer/linux64/flash_player_ppapi_linux.x86_64.tar.gz"
INSTALLDIR="/usr/lib/pepperflashplugin-nonfree"

workdir=$(mktemp -d)
_cleanup() {
    rm -rf ${workdir}
}
trap "_cleanup" EXIT

cd ${workdir}
curl -# -L "$FPDLURL" | tar xzf -
[ ! -d "${INSTALLDIR}" ] && mkdir -p "${INSTALLDIR}"
for f in libpepflashplayer.so manifest.json; do
    [ -f "$f" ] && sudo install -v --backup=simple "$f" "${INSTALLDIR}"
done
